### ISSUE TITLE
Scale visibility based on time

### ISSUE THREAD

**Issue by tanaaKa** [Njpatman/Coalition-Enfusion-UI#44]
Name tags should have max brightness based on world illumination values. Visibility distance should also be capped at a lower value when dark.

**Comment by Quailsnap** [comment]
Is this meant to make nametags present but hard-to-see when it's dark out? I don't think it's great UX to make things UI elements half-visible, and you'll also face moments where someone is standing under a lamppost but you still can't read their dim nametag just because it's night-time. I tried something similar with WH nametags, ages ago, and it varied between ugly and unreadable.

Regarding the second part, visibility distance in general -- ACE3 has an old implementation here that measures ambient light if you want to find it for each unit in FoV. Not sure how viable in terms of functions available and performance. It's in SQF, but may provide some process insight:
https://github.com/acemod/ACE3/blob/41cfed9bd28cd4f8c368007207a1f52c6b3ff2d1/addons/map/functions/fnc_determineMapLight.sqf#L57

**Comment by tanaaKa** [comment]
This is the only answer to this problem:
![image](https://github.com/CoalitionArma/Coalition-Squad-Interface/assets/9407533/6cabb235-40cd-475e-bb1f-c17d322c7356)

Nametags should not show players before players are visible.

**Comment by Quailsnap** [comment]
Totally true, and that would be fixed by nametag range being shorter at night (for those without NODs). That said, be careful making them more transparent/darker at night, because they may be hard to read when directly illuminated by a flashlight or other light source.

**Comment by Njpatman** [comment]
I wonder if there's a way to check the base character's specular level so we can check that level locally and see if the player can actually see another player before displaying the nametag.

**Comment by Quailsnap** [comment]
Do you already do FoV culling?

**Comment by tanaaKa** [comment]
We're using BI logic, so yes.

**Comment by Njpatman** [comment]
I have looked into this and don't believe something like this is possible. I will contact some arma devs to see what kind of input they can give.

**Comment by Njpatman** [comment]
There's some visibility values saved in clothing components in 1.2, will look into it after experimental comes to the main game
